name: Run Azure Login with OIDC
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            #creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
            #creds: '${{secrets.AZURE_CREDS}}'
            creds: '{"clientId":"${{ secrets.CLIENT_ID_AR }}","clientSecret":"${{ secrets.CLIENT_SECRET_AR }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
            enable-AzPSSession: true

        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
             azPSVersion: "latest"
             
        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               New-Item -Path ${{ github.workspace }} -Name "testfile2.txt" -ItemType "file" -Value "This is a text string."
             azPSVersion: "latest" 
             
        - name: 'Create file on Blob'
          uses: azure/powershell@v1
          with:
             inlineScript: |
                  $storageaccountname="myuniquemadstorage120922"
                  $containername="testgithub"
                  $resourcegroup="bicepRG"
                  #Get the Azure Storage account context
                  #$storagecontext = (Get-AzStorageAccount -ResourceGroupName $resourcegroup -Name $storageaccountname)
                  Get-AzStorageAccount -Name $storageaccountname -ResourceGroupName $resourcegroup |
                  Get-AzStorageContainer -Name $containername |
                  Set-AzStorageBlobContent -File '${{ github.workspace }}\testfile2.txt' -Blob 'testfile2.txt'
                  #Get-AzStorageBlob -Container $containername -Context $storagecontext | Select-Object -Property Name
             azPSVersion: "latest"
